---
title: "N samples test"
author: "KSA"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  error = FALSE,
  fig.width = 12,
  fig.height = 10,
  cache = FALSE
)

require("data.table")
require("ampvis2")

if (interactive()) {
  if (!grepl("data/nsamplestest$", getwd())) {
    setwd("data/nsamplestest")
  }
}
```

```{r}
dataset_dir <- "../datasets/Aalborg W/"
#load data, metadata first to sort by date
metadata <- fread(file.path(dataset_dir, "metadata.csv"))[order(Date)]
thedata <- amp_load(
  otutable = file.path(dataset_dir, "ASVtable.csv"),
  metadata = metadata,
  taxonomy = file.path(dataset_dir, "taxonomy.csv")
)

# generate data subsets with only every 2nd, 3rd, and 4th samples
dataset_list <- lapply(2:4, function(x) {
  dataset <- amp_filter_samples(thedata, Date %in% metadata$Date[seq(x, length(metadata$Date), by=x)])

  dataset_folder <- file.path("datasets/", paste(basename(dataset_dir), x))
  dir.create(dataset_folder, recursive = TRUE, showWarnings = FALSE)

  #write out abundance table
  fwrite(
    data.table(
      ASV = rownames(dataset$abund),
      dataset$abund
    ),
    file = file.path(dataset_folder, "ASVtable.csv")
  )

  #write out taxonomy
  fwrite(
    dataset$tax,
    file = file.path(dataset_folder, "taxonomy.csv")
  )

  #write out metadata
  fwrite(
    dataset$metadata,
    bom = TRUE,
    encoding = "UTF-8",
    file = file.path(dataset_folder, "metadata.csv")
  )
  return(dataset)
})
```