---
title: "Immigration data set"
output: md_document
---

# init
```{r}
#load data
library(ampvis2)
library(data.table)
library(tidyverse)
library(lubridate)
library(foreach)
library(doFuture)

if (interactive()) {
  if (!grepl("data/Immigration$", getwd())) {
    setwd("data/Immigration")
  }
}
```

# load and fix metadata
```{r}
metadata <- openxlsx::read.xlsx(
  "metadata_IDs_complete_20230207.xlsx",
  detectDates = TRUE
)
setDT(metadata)

#adjust columns
metadata[, Replicate := as.integer(Replicate)]
metadata[, SampleDate := ymd(SampleDate)]
metadata[, YearWeek := paste(year(SampleDate), week(SampleDate), sep = "-")]

#ensure names are consistent from the same WWTPs
metadata[
  ,
  SampleSite := str_replace_all(
    SampleSite,
    c(
      "Aalborg West" = "Aalborg W",
      "Esbjerg West" = "Esbjerg W",
      "Naestved" = "Næstved"
    )
  )
]
#Aalborg West started with S::Select for 6 time points,
#will be different than usual and mess up any predictions, so remove
metadata <- metadata[
  !LineAS %chin% "S::Select" &
    SampleContent %chin% c("IWW", "AS") &
    !grepl("extneg|pcrpos|pcrneg", LibraryID, ignore.case = TRUE) &
    !PrimarySettler %chin% "before"
]

#each WWTP must have both IWW+AS samples
metadata <- metadata[
  ,
  .SD[
    !length(unique(SampleContent)) != 2
  ],
  by = "SampleSite"
]

#Damhusåen has 4 separate AS lines with the same IWW
metadata[
  SampleSite == "Damhusåen" &
    SampleContent == "AS",
  SampleSite := paste(SampleSite, LineAS, sep = "-")
]

#Filter replicates, just use the first for each time point
metadata <- metadata[
  ,
  .SD[1],
  by = c("SampleSite", "YearWeek", "SampleContent"),
  .SDcols = c("SampleDate", "SampleID")
]

#Reorder with Sample ID's first
metadata <- metadata[
  ,
  c(
    "SampleID",
    "SampleSite",
    "SampleDate",
    "YearWeek",
    "SampleContent"
  )
]

#Filter time points without both IWW+AS pair of samples.
metadata_pairs <- metadata[
  ,
  .SD[
    length(unique(SampleContent)) == 2
  ],
  by = c("SampleSite", "YearWeek")
]
```

# load with ampvis2
```{r}
d <- amp_load(
  otutable = "ASVtable.zip",
  metadata = metadata,
  taxonomy = "ASVs.R1.sintax.zip",
  fasta = "ASVs.R1.zip",
)
```

# create fake samples filling in with -1 abundances where no matching IWW+AS pair
```{r}
# for each WWTP ensure there's a pair of IWW+AS in metadata
# even though not present in abundance table. "Densify"/interpolate
full_metadata <- d$metadata %>%
  group_by(SampleSite) %>%
  expand(YearWeek, SampleContent) %>%
  data.table()

# merge with sparse metadata
full_metadata <- merge(
  full_metadata,
  d$metadata,
  by = c("SampleSite", "YearWeek", "SampleContent"),
  all.x = TRUE
)

#remove fake samples where there's an IWW sample but no AS (can't predict AS with onle -1's)
full_metadata <- full_metadata[!(is.na(SampleID) & SampleContent == "AS")]

# create sample ID's based on wwtp+year+week+location
full_metadata[, oldSampleID := factor(SampleID, levels = colnames(d$abund))]
full_metadata[
  ,
  SampleID := paste(
    SampleSite,
    YearWeek,
    SampleContent
  )
]

# fill in dates from the twin when missing
full_metadata[
  ,
  SampleDate := if(any(is.na(SampleDate))) {
    na.omit(SampleDate)[1]
  } else {
    SampleDate
  },
  by = c("SampleSite", "YearWeek")]

# reorder based on abund
setorder(
  full_metadata,
  oldSampleID
)

# rename columns in abund based on new sample IDs and add missing ones with -1
colnames(d$abund) <- full_metadata[oldSampleID %in% colnames(d$abund), SampleID]
d$abund[, full_metadata[!SampleID %chin% colnames(d$abund), SampleID]] <- -1

# ensure order is the same and they contain the same sample IDs
d$abund <- d$abund[, full_metadata[, SampleID]]
full_metadata <- full_metadata[
  ,
  c(
    "SampleID",
    "oldSampleID",
    "SampleSite",
    "SampleDate",
    "YearWeek",
    "SampleContent"
  )
]
setDF(full_metadata, rownames = full_metadata[, SampleID])
d$metadata <- full_metadata
```

# Sample overview, filtered
```{r}
ggplot(
  metadata_pairs,
  aes(x = SampleDate, y = SampleContent, color = SampleContent)
) +
  geom_point() +
  facet_grid(rows = vars(SampleSite)) +
  scale_x_date(date_breaks = "months") +
  theme(axis.text.x = element_text(angle = 90))
ggsave(file.path("overview plots", "sample_overview.png"), height = 18, width = 12)
```

# Sample overview, unmatched
```{r}
ggplot(
  metadata,
  aes(x = SampleDate, y = SampleContent, color = SampleContent)
) +
  geom_point() +
  facet_grid(rows = vars(SampleSite)) +
  scale_x_date(date_breaks = "months") +
  theme(axis.text.x = element_text(angle = 90))
ggsave(file.path("overview plots", "sample_overview_unfiltered.png"), height = 18, width = 12)
```

# Sample overview, with fake abundances (-1)
```{r}
ggplot(
  d$metadata,
  aes(x = SampleDate, y = SampleContent, color = SampleContent)
) +
  geom_point() +
  facet_grid(rows = vars(SampleSite)) +
  scale_x_date(date_breaks = "months") +
  theme(axis.text.x = element_text(angle = 90))
ggsave(file.path("overview plots", "sample_overview_unfiltered_fakes.png"), height = 18, width = 12)
```

# split into separate files for each WWTP
```{r}
# remove data from WWTPs with no twins (hasn't been sequenced yet I guess)
# mainly esbjerg w+fredericia
metadata_twins <- d$metadata %>%
  group_by(SampleSite) %>%
  filter(length(unique(SampleContent)) > 1)
ds <- amp_filter_samples(
  d,
  SampleID %in% metadata_twins$SampleID
)
future::plan(future::multisession, workers = 16)

outlist <- foreach(
  wwtp = unique(ds$metadata$SampleSite)
) %dofuture% {
    message("Dataset: ", wwtp)
    if(!grepl("^Damhus", wwtp)) {
      dataset <- filter_otus(
        amp_subset_samples(
          ds,
          SampleSite %chin% wwtp,
          normalise = FALSE
        ),
        0.1
      )

      #unfiltered
      dataset_IWW <- amp_subset_samples(
        dataset,
        SampleContent %chin% "IWW",
        removeAbsentOTUs = FALSE
      )
      dataset_AS <- amp_subset_samples(
        dataset,
        SampleContent %chin% "AS",
        removeAbsentOTUs = FALSE
      )

      #filtered
      dataset_filtered <- amp_subset_samples(
        dataset,
        oldSampleID %in% metadata_pairs$SampleID,
        removeAbsentOTUs = FALSE
      )
      dataset_filt_IWW <- amp_subset_samples(
        dataset_filtered,
        SampleContent %chin% "IWW",
        removeAbsentOTUs = FALSE
      )
      dataset_filt_AS <- amp_subset_samples(
        dataset_filtered,
        SampleContent %chin% "AS",
        removeAbsentOTUs = FALSE
      )

      exported_data_dir <- "datasets"

      dataset_dir_IWW <- file.path(exported_data_dir, "unfiltered", wwtp, "IWW")
      dataset_dir_AS <- file.path(exported_data_dir, "unfiltered", wwtp, "AS")
      dataset_dir_filt_IWW <- file.path(exported_data_dir, "filtered", wwtp, "IWW")
      dataset_dir_filt_AS <- file.path(exported_data_dir, "filtered", wwtp, "AS")

      dir.create(dataset_dir_IWW, mode = "0775", recursive = TRUE)
      dir.create(dataset_dir_AS, mode = "0775", recursive = TRUE)
      dir.create(dataset_dir_filt_IWW, mode = "0775", recursive = TRUE)
      dir.create(dataset_dir_filt_AS, mode = "0775", recursive = TRUE)

      #write out abundance tables
      #IWW
      fwrite(
        data.table(
          ASV = rownames(dataset_IWW$abund),
          dataset_IWW$abund
        ),
        file = file.path(dataset_dir_IWW, "ASVtable.csv")
      )
      fwrite(
        data.table(
          ASV = rownames(dataset_filt_IWW$abund),
          dataset_filt_IWW$abund
        ),
        file = file.path(dataset_dir_filt_IWW, "ASVtable.csv")
      )
      #AS
      fwrite(
        data.table(
          ASV = rownames(dataset_AS$abund),
          dataset_AS$abund
        ),
        file = file.path(dataset_dir_AS, "ASVtable.csv")
      )
      fwrite(
        data.table(
          ASV = rownames(dataset_filt_AS$abund),
          dataset_filt_AS$abund
        ),
        file = file.path(dataset_dir_filt_AS, "ASVtable.csv")
      )

      #write out taxonomy
      #IWW
      fwrite(
        dataset_IWW$tax,
        file = file.path(dataset_dir_IWW, "taxonomy.csv")
      )
      fwrite(
        dataset_filt_IWW$tax,
        file = file.path(dataset_dir_filt_IWW, "taxonomy.csv")
      )
      #AS
      fwrite(
        dataset_AS$tax,
        file = file.path(dataset_dir_AS, "taxonomy.csv")
      )
      fwrite(
        dataset_filt_AS$tax,
        file = file.path(dataset_dir_filt_AS, "taxonomy.csv")
      )

      #write out metadata
      #IWW
      fwrite(
        dataset_IWW$metadata,
        file = file.path(dataset_dir_IWW, "metadata.csv")
      )
      fwrite(
        dataset_filt_IWW$metadata,
        file = file.path(dataset_dir_filt_IWW, "metadata.csv")
      )
      #AS
      fwrite(
        dataset_AS$metadata,
        file = file.path(dataset_dir_AS, "metadata.csv")
      )
      fwrite(
        dataset_filt_AS$metadata,
        file = file.path(dataset_dir_filt_AS, "metadata.csv")
      )

      dataset
    }
  }
```
