---
title: "Reformat data to be compatible with ampvis2"
output: md_document
---

# init
```{r}
#load data
library(openxlsx)
library(data.table)
library(lubridate)
# need at least data.table version 1.14.99 to allow writing files with encoding
if (packageVersion("data.table") < "1.14.99") {
  stop("data.table must be version 1.14.99 or later. Upgrade with \"data.table::update_dev_pkg()\" or \"install.packages('data.table', repos='https://rdatatable.gitlab.io/data.table', ref = '1.14.99')\" if it's not available on CRAN for your R version.")
}

if (interactive()) {
  if (!grepl("data/caporaso_et_al_2011$", getwd())) {
    setwd("data/caporaso_et_al_2011")
  }
}
```

# Load data, reformat, export
```{r}
# metadata, only need sample IDs and Dates
metadata <- fread("original/M3_gut_metadata.tsv")

# Generate artificial dates by adding 1.jan 2010 with the SampleDay column
metadata[, Date := as_date("2010", format = "%Y") + SampleDay]

file_path <- file.path("reformatted", "metadata.csv")
fwrite(metadata, file_path)

# abundance table, transpose, write out
abund <- fread("original/M3_gut_genus.tsv", data.table = FALSE)
colnames(abund)[1] <- "OTU"
file_path <- file.path("reformatted", "ASVtable.csv")
dir.create(dirname(file_path), showWarnings = FALSE, recursive = TRUE)
fwrite(abund[, c(1:(ncol(abund)-7))], file_path)

# taxonomy
tax <- abund[,c(1,(ncol(abund)-6):ncol(abund))]
file_path <- file.path("reformatted", "taxonomy.csv")
dir.create(dirname(file_path), showWarnings = FALSE, recursive = TRUE)
fwrite(tax, file_path)
```
