---
title: "calculate averages"
author: "DSW"
date: "5 dec 2018"
output: html_document
---


## Importing data

```{r, warning=FALSE, message=FALSE}


flowdata <- read.delim("flow_RL.txt", check.names = FALSE,dec = ",")
influentdata <- read.delim("influent_data_RL.txt", check.names = FALSE,dec = ",")
influentpHdata <- read.delim("RL_pH_temp.txt", check.names = FALSE,dec = ",")
LAlabdata <- read.delim("RL_LA_tank.txt", check.names = FALSE,dec = ",")
DOLAdata <- read.delim("DO1_RL.txt", check.names = FALSE,dec = ",")
DOLBdata <- read.delim("DO2_RL.txt", check.names = FALSE,dec = ",")
DOLCdata <- read.delim("DO3_RL.txt", check.names = FALSE,dec = ",")
metal_dosing <- read.delim("RL_metal.txt", check.names = FALSE,dec = ",")
effluentflowdata <- read.delim("RL_effluent_flow_measurements.txt", check.names = FALSE,dec = ",")
effluentmeasurementsdata <- read.delim("RL_effluent_measurements.txt", check.names = FALSE,dec = ",")
SS_tank_data <- read.delim("RL_SS_tank.txt", check.names = FALSE,dec = ",")
RAS_data <- read.delim("SSRAS_RL.txt", check.names = FALSE,dec = ",")




```


## Calculating daily avegares

```{r, warning=FALSE, message=FALSE}

library(plyr)
library(dplyr)
library(tidyr)
library(tidyverse)


#Lynetten metadata


##DO_all_lines

split_data<- colsplit(DOLAdata$Time," ",c("Date","Hours"))
bind_data<- cbind(DOLAdata,split_data)
bind_data$Date <- as.Date(bind_data$Date, format = c("%d-%m-%Y"))

bind_data[bind_data==0] <- NA
DOLA5sp <- subset(bind_data, select = c(3, 6, 7))
DOLA5value <- subset(bind_data, select = c(2, 6, 7))
DOLA6sp <- subset(bind_data, select = c(5, 6, 7))
DOLA6value <- subset(bind_data, select = c(4, 6, 7))

DOLA5sp<- drop_na(DOLA5sp)
DOLA5value<- drop_na(DOLA5value)
DOLA6sp<- drop_na(DOLA6sp)
DOLA6value<- drop_na(DOLA6value)

names(DOLA5sp)[names(DOLA5sp) == "DO_Line_A5_setpoint_[mg/l]"] <- "DO_LA_sp"
names(DOLA6sp)[names(DOLA6sp) == "DO_Line_A6_setpoint_[mg/l]"] <- "DO_LA_sp"
names(DOLA5value)[names(DOLA5value) == "DO_Line_A5_value_[mg/l]"] <- "DO_LA"
names(DOLA6value)[names(DOLA6value) == "DO_Line_A6_value_[mg/l]"] <- "DO_LA"

DOLAsp <- rbind(DOLA5sp,DOLA6sp)
  
DOLA <- rbind(DOLA5value,DOLA6value)


mean_DOLAsp <- ddply(DOLAsp, .(Date), summarise, daily_mean_DOLAsp = mean(DO_LA_sp))
mean_DOLA <- ddply(DOLA, .(Date), summarise, daily_mean_DOLAvalue = mean(DO_LA))

mean_DOLAsp <- mean_DOLAsp %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))
mean_DOLA <- mean_DOLA %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))




split_data<- colsplit(DOLBdata$Time," ",c("Date","Hours"))
bind_data<- cbind(DOLBdata,split_data)
bind_data$Date <- as.Date(bind_data$Date, format = c("%d-%m-%Y"))

bind_data[bind_data==0] <- NA
DOLB3sp <- subset(bind_data, select = c(3, 6, 7))
DOLB3value <- subset(bind_data, select = c(2, 6, 7))
DOLB4sp <- subset(bind_data, select = c(5, 6, 7))
DOLB4value <- subset(bind_data, select = c(4, 6, 7))

DOLB3sp<- drop_na(DOLB3sp)
DOLB3value<- drop_na(DOLB3value)
DOLB4sp<- drop_na(DOLB4sp)
DOLB4value<- drop_na(DOLB4value)

names(DOLB3sp)[names(DOLB3sp) == "DO_Line_B3_setpoint_[mg/l]"] <- "DO_LB_sp"
names(DOLB4sp)[names(DOLB4sp) == "DO_Line_B4_setpoint_[mg/l]"] <- "DO_LB_sp"
names(DOLB3value)[names(DOLB3value) == "DO_Line_B3_value_[mg/l]"] <- "DO_LB"
names(DOLB4value)[names(DOLB4value) == "DO_Line_B4_value_[mg/l]"] <- "DO_LB"

DOLBsp <- rbind(DOLB3sp,DOLB4sp)
  
DOLB <- rbind(DOLB3value,DOLB4value)


mean_DOLBsp <- ddply(DOLBsp, .(Date), summarise, daily_mean_DOLBsp = mean(DO_LB_sp))
mean_DOLB <- ddply(DOLB, .(Date), summarise, daily_mean_DOLBvalue = mean(DO_LB))

mean_DOLBsp <- mean_DOLBsp %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))
mean_DOLB <- mean_DOLB %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))





split_data<- colsplit(DOLCdata$Time," ",c("Date","Hours"))
bind_data<- cbind(DOLCdata,split_data)
bind_data$Date <- as.Date(bind_data$Date, format = c("%d-%m-%Y"))

bind_data[bind_data==0] <- NA
DOLC5sp <- subset(bind_data, select = c(3, 6, 7))
DOLC5value <- subset(bind_data, select = c(2, 6, 7))
DOLC6sp <- subset(bind_data, select = c(5, 6, 7))
DOLC6value <- subset(bind_data, select = c(4, 6, 7))

DOLC5sp<- drop_na(DOLC5sp)
DOLC5value<- drop_na(DOLC5value)
DOLC6sp<- drop_na(DOLC6sp)
DOLC6value<- drop_na(DOLC6value)

names(DOLC5sp)[names(DOLC5sp) == "DO_Line_C5_setpoint_[mg/l]"] <- "DO_LC_sp"
names(DOLC6sp)[names(DOLC6sp) == "DO_Line_C6_setpoint_[mg/l]"] <- "DO_LC_sp"
names(DOLC5value)[names(DOLC5value) == "DO_Line_C5_value_[mg/l]"] <- "DO_LC"
names(DOLC6value)[names(DOLC6value) == "DO_Line_C6_value_[mg/l]"] <- "DO_LC"

DOLCsp <- rbind(DOLC5sp,DOLC6sp)
  
DOLC <- rbind(DOLC5value,DOLC6value)


mean_DOLCsp <- ddply(DOLCsp, .(Date), summarise, daily_mean_DOLCsp = mean(DO_LC_sp))
mean_DOLC <- ddply(DOLC, .(Date), summarise, daily_mean_DOLCvalue = mean(DO_LC))

mean_DOLCsp <- mean_DOLCsp %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))
mean_DOLC <- mean_DOLC %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))





bind_DO<- cbind(mean_DOLAsp,mean_DOLA$daily_mean_DOLAvalue,mean_DOLBsp$daily_mean_DOLBsp,mean_DOLB$daily_mean_DOLBvalue,mean_DOLCsp$daily_mean_DOLCsp,mean_DOLC$daily_mean_DOLCvalue)
names(bind_DO)[names(bind_DO) == "daily_mean_DOLAsp"] <- "DO_Line_A_setpoint_[mg/l]" 
names(bind_DO)[names(bind_DO) == "mean_DOLA$daily_mean_DOLAvalue"] <- "DO_Line_A_value_[mg/l]"
names(bind_DO)[names(bind_DO) == "mean_DOLBsp$daily_mean_DOLBsp"] <- "DO_Line_B_setpoint_[mg/l]"
names(bind_DO)[names(bind_DO) == "mean_DOLB$daily_mean_DOLBvalue"] <- "DO_Line_B_value_[mg/l]"
names(bind_DO)[names(bind_DO) == "mean_DOLCsp$daily_mean_DOLCsp"] <- "DO_Line_C_setpoint_[mg/l]"
names(bind_DO)[names(bind_DO) == "mean_DOLC$daily_mean_DOLCvalue"] <- "DO_Line_C_value_[mg/l]"




bind_DO <- format(bind_DO, decimal.mark=",")

bind_DO <-  subset(bind_DO, Date < ("2020-03-31") )
bind_DO <-  subset(bind_DO,Date > ("2016-12-31"))


##Influent

influentdata$Date <- as.Date(influentdata$Date, format = c("%d-%m-%Y"))
influentdata_expand <- influentdata

influentdata_expand <- influentdata_expand %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))



influentpHdata$Date <- as.Date(influentpHdata$Date, format = c("%d-%m-%Y"))
influentpHdata_expand <- influentpHdata

influentpHdata_expand <- influentpHdata_expand %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))

#influentpHdata_expand <-  subset(influentpHdata_expand, Date < ("2019-11-06") )
#influentpHdata_expand <-  subset(influentpHdata_expand,Date > ("2016-12-31"))


##Process tank lab


LAlabdata$Date <- as.Date(LAlabdata$Date, format = c("%d-%m-%Y"))

LAlabdata_expand <- LAlabdata %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))




##RAS and SS tank


SS_tank_data$Date <- as.Date(SS_tank_data$Date, format = c("%d-%m-%Y"))
SS_tank_data_expand <- SS_tank_data

SS_tank_data_expand <- SS_tank_data_expand %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))



split_data<- colsplit(RAS_data$Time," ",c("Date","Hours"))
bind_data<- cbind(RAS_data,split_data)
bind_data$Date <- as.Date(bind_data$Date, format = c("%d-%m-%Y"))

bind_data[bind_data==0] <- NA
RASA <- subset(bind_data, select = c(6, 7, 8))
RASB <- subset(bind_data, select = c(5, 7, 8))
RASC <- subset(bind_data, select = c(4, 7, 8))
RASD <- subset(bind_data, select = c(3, 7, 8))
RASE <- subset(bind_data, select = c(2, 7, 8))



RASA<- drop_na(RASA)
RASB<- drop_na(RASB)
RASC<- drop_na(RASC)
RASD<- drop_na(RASD)
RASE<- drop_na(RASE)

names(RASA)[names(RASA) == "SS_RAS_Line_A_[g/l]"] <- "RAS_A"
names(RASB)[names(RASB) == "SS_RAS_Line_B_[g/l]"] <- "RAS_B"
names(RASC)[names(RASC) == "SS_RAS_Line_C_[g/l]"] <- "RAS_C"
names(RASD)[names(RASD) == "SS_RAS_Line_D_[g/l]"] <- "RAS_D"
names(RASE)[names(RASE) == "SS_RAS_Line_E_[g/l]"] <- "RAS_E"


mean_RASA <- ddply(RASA, .(Date), summarise, daily_mean_RASA = mean(RAS_A))
mean_RASB <- ddply(RASB, .(Date), summarise, daily_mean_RASB = mean(RAS_B))
mean_RASC <- ddply(RASC, .(Date), summarise, daily_mean_RASC = mean(RAS_C))
mean_RASD <- ddply(RASD, .(Date), summarise, daily_mean_RASD = mean(RAS_D))
mean_RASE <- ddply(RASE, .(Date), summarise, daily_mean_RASE = mean(RAS_E))




mean_RASA <- mean_RASA %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))
mean_RASB <- mean_RASB %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))
mean_RASC <- mean_RASC %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))
mean_RASD <- mean_RASD %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))
mean_RASE <- mean_RASE %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))



bind_RAS<- cbind(mean_RASA,mean_RASB$daily_mean_RASB,mean_RASC$daily_mean_RASC,mean_RASD$daily_mean_RASD,mean_RASE$daily_mean_RASE)
names(bind_RAS)[names(bind_RAS) == "daily_mean_RASA"] <- "SS_RAS_Line_A_[g/l]" 
names(bind_RAS)[names(bind_RAS) == "mean_RASB$daily_mean_RASB"] <- "SS_RAS_Line_B_[g/l]"
names(bind_RAS)[names(bind_RAS) == "mean_RASC$daily_mean_RASC"] <- "SS_RAS_Line_C_[g/l]"
names(bind_RAS)[names(bind_RAS) == "mean_RASD$daily_mean_RASD"] <- "SS_RAS_Line_D_[g/l]"
names(bind_RAS)[names(bind_RAS) == "mean_RASE$daily_mean_RASE"] <- "SS_RAS_Line_E_[g/l]"




bind_RAS <- format(bind_RAS, decimal.mark=",")

bind_RAS <-  subset(bind_DO, Date < ("2020-03-31") )
bind_RAS <-  subset(bind_RAS,Date > ("2016-12-31"))




#RAS_SS_tank_data_expand <-  subset(RAS_SS_tank_data_expand, Date < ("2019-11-06") )
#RAS_SS_tank_data_expand <-  subset(RAS_SS_tank_data_expand,Date > ("2016-12-31"))



##Effluent data

effluentflowdata$Date <- as.Date(effluentflowdata$Date, format = c("%d-%m-%Y"))
effluentflowdata_expand <- effluentflowdata

effluentflowdata_expand <- effluentflowdata_expand %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))

effluentmeasurementsdata$Date <- as.Date(effluentmeasurementsdata$Date, format = c("%d-%m-%Y"))
effluentmeasurementsdata_expand <- effluentmeasurementsdata

effluentmeasurementsdata_expand <- effluentmeasurementsdata_expand %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))




#effluentonlinedata_expand <-  subset(effluentonlinedata_expand, Date < ("2019-11-06") )
#effluentonlinedata_expand <-  subset(effluentonlinedata_expand,Date > ("2016-12-31"))

##Metal and C dosing data


metal_dosing$Date <- as.Date(metal_dosing$Date, format = c("%d-%m-%Y"))
metal_dosing_expand <- metal_dosing

metal_dosing_expand <- metal_dosing_expand %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))

#metal_C_dosing_expand <-  subset(metal_C_dosing_expand, Date < ("2019-11-06") )
#metal_C_dosing_expand <-  subset(metal_C_dosing_expand,Date > ("2016-12-31"))


##Flow data


flowdata$Date <- as.Date(flowdata$Date, format = c("%d-%m-%Y"))
flowdata_expand <- flowdata

flowdata_expand <- flowdata_expand %>%
       complete(Date = seq.Date(as.Date("2017-01-01"), as.Date("2020-03-30"), by = "day"))





##Bind all data

bind_all <- cbind(flowdata_expand,influentpHdata_expand[,2:4],influentdata_expand[,2:10],LAlabdata_expand[,2:8], bind_RAS[,2:6],SS_tank_data_expand[,2:4],bind_DO[,2:7],metal_dosing_expand[,2:5],effluentflowdata_expand[,2:2],effluentmeasurementsdata_expand[,2:10])


#write.table(bind_all, file = "AAW_metadata_2015_2018.txt", sep = "\t",
    #        row.names = FALSE)
#check <- read.delim("AAW_metadata_2015_2018.txt", check.names = FALSE)


bind_all <- format(bind_all, decimal.mark=",")

write.table(bind_all, file = "bind_all.csv",sep = "\t", row.names = F)



```

