---
title: "Reformat data to be compatible with ampvis2"
output: md_document
---

# init
```{r}
#load data
library(openxlsx)
library(data.table)
library(lubridate)
# need at least data.table version 1.14.99 to allow writing files with encoding
if (packageVersion("data.table") < "1.14.99") {
  stop("data.table must be version 1.14.99 or later. Upgrade with \"data.table::update_dev_pkg()\" or \"install.packages('data.table', repos='https://rdatatable.gitlab.io/data.table', ref = '1.14.99')\" if it's not available on CRAN for your R version.")
}

if (interactive()) {
  if (!grepl("data/chrismas_et_al_2023$", getwd())) {
    setwd("data/chrismas_et_al_2023")
  }
}
```

# Load data, reformat, export
```{r}
# metadata, only need sample IDs and Dates
metadata <- read.xlsx("original/rspb20222129_si_metadata.xlsx", detectDates = TRUE, cols = c(1,3))
metadata$date <- lubridate::ymd(metadata$date)
colnames(metadata) <- c("SampleID", "Date")
file_path <- file.path("reformatted", "metadata.csv")
fwrite(metadata, file_path)

# abundance table, transpose, write out
abund <- fread("original/l4_OTU_1.csv", data.table = FALSE)
abund <- t(as.matrix(abund))
colnames(abund) <- abund[1, ]
abund <- abund[-1, ]
abund <- data.table(ASV = rownames(abund), abund)
file_path <- file.path("reformatted", "ASVtable.csv")
dir.create(dirname(file_path), showWarnings = FALSE, recursive = TRUE)
fwrite(abund, file_path)

# taxonomy, eukaryotes, so remove all levels but ASV+Genus+Species, write out
tax <- openxlsx::read.xlsx("original/rspb20222129_si_taxomony.xlsx")
setDT(tax)
# remove uncultured and partial Species, remove comments (in a Species name, WHY SILVA? WHY???)
tax[, Species := gsub(".*[uU]ncultured.*|.*partial.*|;.*$", "", Species)]
tax[Species == "", Species := ASV]
# first two words are genus+species
tax[, Species := sapply(strsplit(Species, " "), function(x) if(length(x) >= 2) paste(x[1:2], collapse = " ") else return(x))]
file_path <- file.path("reformatted", "taxonomy.csv")
dir.create(dirname(file_path), showWarnings = FALSE, recursive = TRUE)
fwrite(tax[, c("ASV", "Genus", "Species")], file_path)
```
